# Complete Pandas Data Analysis Learning Notebook

## Using E-commerce Sales Dataset


### Table of Contents

**Introduction**
- What is Pandas and Why Use It?

**Module B: Pandas – Introduction to Data Structures**
- Introduction to Pandas
- Pandas Series
  - Creating a Series
  - Basic attributes (index, values)
- Pandas DataFrame
  - Creating a DataFrame (from dictionary of lists, list of dictionaries)
  - Understanding the structure: rows, columns, index

**Module C: Loading & Inspecting Data with Pandas**
- Loading Data
  - Reading data from CSV files (pd.read_csv())
  - Common parameters like sep, header
  - Quick look at other formats (Excel - pd.read_excel())
- Inspecting DataFrames
  - `df.head()`, `df.tail()` – looking at data
  - `df.info()` – data types, non-null counts
  - `df.describe()` – summary statistics for numerical columns
  - `df.shape` – dimensions
  - `df.dtypes` – data types of columns
  - `df.columns` – viewing column names
  - `df.index` – viewing the index

**Module D: Basic Data Selection in Pandas**
- Column Selection
  - Selecting a single column (returns a Series)
  - Selecting multiple columns (returns a DataFrame)
- Row Selection with loc and iloc
  - `df.loc[]`: Label-based indexing
  - `df.iloc[]`: Integer-position based indexing
  - Focus on common use cases for selecting specific rows/ranges

**Module E: Advanced Selection & Data Cleaning with Pandas**
- Quick Recap of Previous Modules
- Boolean Indexing (Conditional Selection)
  - Creating boolean masks based on column values
  - Applying masks to filter DataFrames
  - Combining conditions (& for AND, | for OR)
- Handling Missing Data
  - Identifying missing values: df.isnull().sum()
  - Dropping missing values: df.dropna()
  - Filling missing values: df.fillna()
- Handling Duplicates
  - Identifying duplicates: df.duplicated()
  - Dropping duplicates: df.drop_duplicates()
- Basic Data Type Conversion
  - `df['column'].astype()

**Module F: Data Grouping & Aggregation**
- The groupby() Operation
  - Concept of Split-Apply-Combine
  - Grouping by one or more columns
  - Applying aggregation functions: sum(), mean(), median(), count(), std(), size(), agg()
  - Simple examples to illustrate its power

In [ ]:

# =============================================================================
# INTRODUCTION: What is Pandas and Why Use It?
# =============================================================================

# Introduction: What is Pandas and Why Use It?

## What is Pandas?

Pandas is a powerful, open-source data analysis and manipulation library for Python. 
It provides data structures and functions needed to work with structured data quickly and effectively.

The name "Pandas" comes from "Panel Data" and is also a play on "Python Data Analysis."

## Why Use Pandas for Data Analysis?

1. **Easy Data Loading**: Read data from various formats (CSV, Excel, JSON, SQL databases)
2. **Data Cleaning**: Handle missing values, duplicates, and data type issues
3. **Data Manipulation**: Filter, sort, group, and transform data easily
4. **Data Analysis**: Perform statistical operations and aggregations
5. **Integration**: Works seamlessly with other Python libraries (NumPy, Matplotlib, Scikit-learn)
6. **Performance**: Built on NumPy for fast numerical operations

## Core Data Structures

Pandas provides two main data structures:
- **Series**: 1-dimensional labeled array (like a column in a spreadsheet)
- **DataFrame**: 2-dimensional labeled data structure (like a spreadsheet or SQL table)

Let's dive in and start learning!

In [ ]:

# =============================================================================
# MODULE B: PANDAS – INTRODUCTION TO DATA STRUCTURES
# =============================================================================

# Module B: Pandas – Introduction to Data Structures

## Introduction to Pandas

Before we work with real data, let's understand the fundamental building blocks of pandas.

In [1]:
import pandas as pd
import numpy as np

# Check pandas version
print(f"Pandas version: {pd.__version__}")

Pandas version: 2.2.3

## Pandas Series

A Series is a one-dimensional labeled array capable of holding any data type.
Think of it as a single column from a spreadsheet.

### Creating a Series

In [21]:
# Creating a Series from a list
sales_data = [1200, 1500, 1100, 1800, 1400]
sales_data

[1200, 1500, 1100, 1800, 1400]

In [22]:
np.array(sales_data)

array([1200, 1500, 1100, 1800, 1400])

In [23]:
sales_series = pd.Series(sales_data)
sales_series

0    1200
1    1500
2    1100
3    1800
4    1400
dtype: int64

In [24]:
print("Sales Series:")
print(sales_series)
print()

Sales Series:
0    1200
1    1500
2    1100
3    1800
4    1400
dtype: int64

In [25]:
# Creating a Series with custom index
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May']
monthly_sales = pd.Series(sales_data, index=months)

In [26]:
print("Monthly Sales Series:")
print(monthly_sales)
print()

Monthly Sales Series:
Jan    1200
Feb    1500
Mar    1100
Apr    1800
May    1400
dtype: int64

In [27]:
# Creating a Series from a dictionary
product_prices = {'iPhone': 999, 'Samsung Galaxy': 899, 'iPad': 599}
price_series = pd.Series(product_prices)
print("Product Prices Series:")
print(price_series)
print()

Product Prices Series:
iPhone            999
Samsung Galaxy    899
iPad              599
dtype: int64

### Basic Series Attributes

Let's explore the basic attributes of a Series:

In [32]:
monthly_sales

Jan    1200
Feb    1500
Mar    1100
Apr    1800
May    1400
dtype: int64

In [30]:
monthly_sales.values

array([1200, 1500, 1100, 1800, 1400], dtype=int64)

In [33]:
monthly_sales.index

Index(['Jan', 'Feb', 'Mar', 'Apr', 'May'], dtype='object')

In [35]:
monthly_sales.dtype

dtype('int64')

In [37]:
monthly_sales.shape

(5,)

In [38]:
monthly_sales.size

5

In [40]:
print("=== Series Attributes ===")
print(f"Values: {monthly_sales.values}")
print(f"Index: {monthly_sales.index}")
print(f"Data Type: {monthly_sales.dtype}")
print(f"Shape: {monthly_sales.shape}")
print(f"Size: {monthly_sales.size}")
print()

=== Series Attributes ===
Values: [1200 1500 1100 1800 1400]
Index: Index(['Jan', 'Feb', 'Mar', 'Apr', 'May'], dtype='object')
Data Type: int64
Shape: (5,)
Size: 5

In [47]:
monthly_sales

Jan    1200
Feb    1500
Mar    1100
Apr    1800
May    1400
dtype: int64

In [53]:
monthly_sales.iloc[2:4]

Mar    1100
Apr    1800
dtype: int64

In [56]:
monthly_sales['Feb':'May']

Feb    1500
Mar    1100
Apr    1800
May    1400
dtype: int64

In [54]:
monthly_sales.loc['Feb':'May']

Feb    1500
Mar    1100
Apr    1800
May    1400
dtype: int64

In [7]:
# Accessing individual elements
print("=== Accessing Series Elements ===")
print(f"January sales: {monthly_sales['Jan']}")
print(f"First element: {monthly_sales.iloc[0]}")
print(f"Last element: {monthly_sales.iloc[-1]}")
print()

=== Accessing Series Elements ===
January sales: 1200
First element: 1200
Last element: 1400

## Pandas DataFrame

A DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.
Think of it as a spreadsheet or SQL table.

### Creating a DataFrame from Dictionary of Lists

In [57]:

# Dictionary of lists approach
customer_data = {
    'customer_id': ['CUST-001', 'CUST-002', 'CUST-003', 'CUST-004'],
    'name': ['John Smith', 'Jane Doe', 'Mike Johnson', 'Sarah Wilson'],
    'age': [25, 32, 28, 35],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'total_spent': [1250.50, 2100.75, 875.25, 1650.00]
}

df_customers = pd.DataFrame(customer_data)
print("Customer DataFrame:")
df_customers

Customer DataFrame:

  customer_id          name  age         city  total_spent
0    CUST-001    John Smith   25     New York      1250.50
1    CUST-002      Jane Doe   32  Los Angeles      2100.75
2    CUST-003  Mike Johnson   28      Chicago       875.25
3    CUST-004  Sarah Wilson   35      Houston      1650.00


### Creating a DataFrame from List of Dictionaries

In [58]:

# List of dictionaries approach
orders_data = [
    {'order_id': 'ORD-001', 'customer': 'John Smith', 'amount': 250.50, 'status': 'Completed'},
    {'order_id': 'ORD-002', 'customer': 'Jane Doe', 'amount': 175.25, 'status': 'Shipped'},
    {'order_id': 'ORD-003', 'customer': 'Mike Johnson', 'amount': 89.99, 'status': 'Processing'},
    {'order_id': 'ORD-004', 'customer': 'Sarah Wilson', 'amount': 320.00, 'status': 'Completed'}
]

df_orders = pd.DataFrame(orders_data)
print("Orders DataFrame:")
df_orders

Orders DataFrame:

  order_id      customer  amount      status
0  ORD-001    John Smith  250.50   Completed
1  ORD-002      Jane Doe  175.25     Shipped
2  ORD-003  Mike Johnson   89.99  Processing
3  ORD-004  Sarah Wilson  320.00   Completed


### Understanding DataFrame Structure: Rows, Columns, Index

In [62]:
df_customers

  customer_id          name  age         city  total_spent
0    CUST-001    John Smith   25     New York      1250.50
1    CUST-002      Jane Doe   32  Los Angeles      2100.75
2    CUST-003  Mike Johnson   28      Chicago       875.25
3    CUST-004  Sarah Wilson   35      Houston      1650.00

In [67]:
list(df_customers.columns)

['customer_id', 'name', 'age', 'city', 'total_spent']

In [68]:
list(df_customers.index)

[0, 1, 2, 3]

In [69]:
df_customers.dtypes

customer_id     object
name            object
age              int64
city            object
total_spent    float64
dtype: object

In [59]:
print("=== DataFrame Structure ===")
print(f"Shape (rows, columns): {df_customers.shape}")
print(f"Columns: {list(df_customers.columns)}")
print(f"Index: {list(df_customers.index)}")
print(f"Data types:\n{df_customers.dtypes}")
print()

=== DataFrame Structure ===
Shape (rows, columns): (4, 5)
Columns: ['customer_id', 'name', 'age', 'city', 'total_spent']
Index: [0, 1, 2, 3]
Data types:
customer_id     object
name            object
age              int64
city            object
total_spent    float64
dtype: object

In [70]:
df_customers

  customer_id          name  age         city  total_spent
0    CUST-001    John Smith   25     New York      1250.50
1    CUST-002      Jane Doe   32  Los Angeles      2100.75
2    CUST-003  Mike Johnson   28      Chicago       875.25
3    CUST-004  Sarah Wilson   35      Houston      1650.00

In [73]:
df_customers['age']

0    25
1    32
2    28
3    35
Name: age, dtype: int64

In [75]:
df_customers['name']

0      John Smith
1        Jane Doe
2    Mike Johnson
3    Sarah Wilson
Name: name, dtype: object

In [76]:
df_customers[['name', 'age']]

           name  age
0    John Smith   25
1      Jane Doe   32
2  Mike Johnson   28
3  Sarah Wilson   35

In [77]:
# Accessing columns and rows
print("=== Accessing DataFrame Elements ===")
print("Customer names (as Series):")
print(df_customers['name'])
print()

=== Accessing DataFrame Elements ===
Customer names (as Series):
0      John Smith
1        Jane Doe
2    Mike Johnson
3    Sarah Wilson
Name: name, dtype: object

In [78]:
df_customers

  customer_id          name  age         city  total_spent
0    CUST-001    John Smith   25     New York      1250.50
1    CUST-002      Jane Doe   32  Los Angeles      2100.75
2    CUST-003  Mike Johnson   28      Chicago       875.25
3    CUST-004  Sarah Wilson   35      Houston      1650.00

In [83]:
df_customers.loc[0:1, 'name']

0    John Smith
1      Jane Doe
Name: name, dtype: object

In [15]:
print("First row (as Series):")
print(df_customers.iloc[0])
print()

First row (as Series):
customer_id      CUST-001
name           John Smith
age                    25
city             New York
total_spent        1250.5
Name: 0, dtype: object

### Exercise: Create Your Own DataFrame

Try creating a DataFrame with product information:
- product_id: `['PROD-001', 'PROD-002', 'PROD-003']`
- product_name: `['Laptop', 'Mouse', 'Keyboard']`
- category: `['Electronics', 'Electronics', 'Electronics']`
- price: `[999.99, 25.99, 79.99]`

In [17]:
# Solution:
product_info = {
    'product_id': ['PROD-001', 'PROD-002', 'PROD-003'],
    'product_name': ['Laptop', 'Mouse', 'Keyboard'],
    'category': ['Electronics', 'Electronics', 'Electronics'],
    'price': [999.99, 25.99, 79.99]
}

df_products = pd.DataFrame(product_info)
print("Product DataFrame (Exercise Solution):")
df_products

Product DataFrame (Exercise Solution):

  product_id product_name     category   price
0   PROD-001       Laptop  Electronics  999.99
1   PROD-002        Mouse  Electronics   25.99
2   PROD-003     Keyboard  Electronics   79.99

In [ ]:
# =============================================================================
# MODULE C: LOADING & INSPECTING DATA WITH PANDAS
# =============================================================================

# Module C: Loading & Inspecting Data with Pandas

Now let's work with real data! We'll load our e-commerce dataset and learn how to inspect it.

## Loading Data

### Reading Data from CSV Files

The most common way to load data into pandas is from CSV files using pd.read_csv().

In [84]:
# Load the e-commerce dataset
df = pd.read_csv('ecommerce_sales_data.csv')
print("✅ Successfully loaded the e-commerce dataset!")
print(f"Dataset shape: {df.shape}")

✅ Successfully loaded the e-commerce dataset!
Dataset shape: (1220, 20)

### Common `pd.read_csv()` Parameters

Let's explore some useful parameters:

In [90]:
# Demonstrate various parameters (using our existing DataFrame as example)
print("=== Common CSV Reading Parameters ===")
print("Basic syntax: pd.read_csv('filename.csv')")
print("Common parameters:")
print("- sep=',': Specify separator (default is comma)")
print("- header=0: Row to use as column names (default is 0)")
print("- index_col=None: Column to use as row labels")
print("- skiprows=0: Number of rows to skip at the beginning")
print("- nrows=None: Number of rows to read")
print("- usecols=None: List of column names to use")
print()

=== Common CSV Reading Parameters ===
Basic syntax: pd.read_csv('filename.csv')
Common parameters:
- sep=',': Specify separator (default is comma)
- header=0: Row to use as column names (default is 0)
- index_col=None: Column to use as row labels
- skiprows=0: Number of rows to skip at the beginning
- nrows=None: Number of rows to read
- usecols=None: List of column names to use

### Quick Look at Other Formats

Pandas can read many file formats:

In [86]:
print("=== Other File Formats Pandas Can Read ===")
print("- Excel: pd.read_excel('file.xlsx')")
print("- JSON: pd.read_json('file.json')")
print("- SQL: pd.read_sql('query', connection)")
print("- HTML: pd.read_html('url')")
print("- Parquet: pd.read_parquet('file.parquet')")
print()

=== Other File Formats Pandas Can Read ===
- Excel: pd.read_excel('file.xlsx')
- JSON: pd.read_json('file.json')
- SQL: pd.read_sql('query', connection)
- HTML: pd.read_html('url')
- Parquet: pd.read_parquet('file.parquet')

## Inspecting DataFrames

Now let's learn the essential methods for exploring our dataset.

### `df.head()` and `df.tail()` – Looking at Data

In [91]:
print("=== First 5 rows (df.head()) ===")
df.head()

=== First 5 rows (df.head()) ===

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
1,ORD-1260,CUST-0293,Angela Lee,angela.lee@email.com,PROD-5706,Dell Laptop,Electronics,HP,882.75,3,2648.25,20.0,2025-02-19,8232 Second Ave,Jacksonville,FL,Canada,Debit Card,Cancelled,74.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
3,ORD-2011,CUST-0177,Paul Thompson,paul.thompson@email.com,PROD-3154,Dumbbell Set,Sports,Nike,49.62,5,248.10,10.0,2024-11-22,8955 First St,Chicago,IL,Canada,Bank Transfer,Processing,74.0
4,ORD-1755,CUST-0011,James Harris,james.harris@email.com,PROD-8882,Tennis Racket,Sports,Under Armour,74.16,1,74.16,25.0,2024-07-31,6685 Elm St,Dallas,TX,UK,Apple Pay,Processing,24.0

In [97]:
print("=== Last 3 rows (df.tail(3)) ===")
df.tail(3)

=== Last 3 rows (df.tail(3)) ===

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
1217,ORD-2131,CUST-0183,Mark Ramirez,mark.ramirez@email.com,PROD-5633,Bed Sheets,Home & Garden,KitchenAid,297.50,3,892.50,15.0,2025-03-14,3664 Second Ave,San Antonio,TX,USA,Apple Pay,Cancelled,71.0
1218,ORD-1861,CUST-0140,Daniel Jones,daniel.jones@email.com,PROD-7964,Bed Sheets,Home & Garden,Cuisinart,61.17,1,61.17,0.0,2023-12-17,7943 Park Rd,Indianapolis,IN,UK,PayPal,Cancelled,55.0
1219,ORD-2127,CUST-0248,James Clark,james.clark@email.com,PROD-6605,MacBook Pro,Electronics,Asus,297.33,4,1189.32,NaN,2024-08-18,1237 Oak Ave,Austin,TX,Australia,Apple Pay,Shipped,18.0


### `df.info()` – Data Types and Non-null Counts

In [98]:
print("=== DataFrame Info (df.info()) ===")
df.info()

=== DataFrame Info (df.info()) ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1220 entries, 0 to 1219
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1220 non-null   object
 1   customer_id       1220 non-null   object
 2   customer_name     1220 non-null   object
 3   customer_email    1168 non-null   object
 4   product_id        1220 non-null   object
 5   product_name      1220 non-null   object
 6   category          1220 non-null   object
 7   brand             1122 non-null   object
 8   price             1220 non-null   float64
 9   quantity          1220 non-null   int64
 10  total_amount      1220 non-null   float64
 11  discount_percent  1017 non-null   float64
 12  order_date        1220 non-null   object
 13  shipping_address  1133 non-null   object
 14  city              1220 non-null   object
 15  state             1220 non-null   object
 16  country           1220 non-null   object
 17  payment_method    1220 non-null   object
 18  order_status      1220 non-null   object
 19  customer_age      1108 non-null   float64
dtypes: float64(4), int64(1), object(15)
memory usage: 190.8+ KB


### `df.describe()` – Summary Statistics for Numerical Columns

In [101]:
print("=== Summary Statistics (df.describe()) ===")
df.describe()

=== Summary Statistics (df.describe()) ===

             price     quantity  total_amount  discount_percent  customer_age
count  1220.000000  1220.000000   1220.000000       1017.000000   1108.000000
mean    256.385598     3.061475    788.981295         12.197640     46.529783
std     409.223878     1.420692   1439.555947          8.578222     16.839377
min       8.150000     1.000000      8.610000          0.000000     18.000000
25%      51.185000     2.000000    123.310000          5.000000     32.000000
50%      96.895000     3.000000    276.820000         10.000000     46.000000
75%     230.130000     4.000000    689.207500         20.000000     61.000000
max    1999.170000     5.000000   9592.800000         25.000000     75.000000

In [102]:
# For a more comprehensive description including non-numeric columns
print("=== Summary Statistics - All Columns (df.describe(include='all')) ===")
df.describe(include='all')

=== Summary Statistics - All Columns (df.describe(include='all')) ===

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
count,1220,1220,1220,1168,1220,1220,1220,1122,1220.000000,1220.000000,1220.000000,1017.000000,1220,1133,1220,1220,1220,1220,1220,1108.000000
unique,1190,294,668,655,1112,39,7,37,NaN,NaN,NaN,NaN,605,1107,18,11,5,5,5,NaN
top,ORD-1049,CUST-0220,Mark Clark,jane.thomas@email.com,PROD-3088,LEGO Set,Beauty,Nike,NaN,NaN,NaN,NaN,2024-09-15,1335 First St,Philadelphia,TX,Australia,Apple Pay,Completed,NaN
freq,3,11,7,7,3,46,195,57,NaN,NaN,NaN,NaN,8,2,81,329,264,264,265,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,256.385598,3.061475,788.981295,12.197640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.529783
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,409.223878,1.420692,1439.555947,8.578222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.839377
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.150000,1.000000,8.610000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.185000,2.000000,123.310000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.895000,3.000000,276.820000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,230.130000,4.000000,689.207500,20.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.170000,5.000000,9592.800000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.000000


### `df.shape` – Dimensions

In [103]:
print("=== DataFrame Dimensions (df.shape) ===")
print(f"Shape: {df.shape}")
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")
print()

=== DataFrame Dimensions (df.shape) ===
Shape: (1220, 20)
Number of rows: 1220
Number of columns: 20


### `df.dtypes` – Data Types of Columns

In [105]:
print("=== Column Data Types (df.dtypes) ===")
print(df.dtypes)
print()

=== Column Data Types (df.dtypes) ===
order_id             object
customer_id          object
customer_name        object
customer_email       object
product_id           object
product_name         object
category             object
brand                object
price               float64
quantity              int64
total_amount        float64
discount_percent    float64
order_date           object
shipping_address     object
city                 object
state                object
country              object
payment_method       object
order_status         object
customer_age        float64
dtype: object


### `df.columns` – Viewing Column Names

In [106]:
print("=== Column Names (df.columns) ===")
print("Columns:", list(df.columns))
print("Number of columns:", len(df.columns))
print()

=== Column Names (df.columns) ===
Columns: ['order_id', 'customer_id', 'customer_name', 'customer_email', 'product_id', 'product_name', 'category', 'brand', 'price', 'quantity', 'total_amount', 'discount_percent', 'order_date', 'shipping_address', 'city', 'state', 'country', 'payment_method', 'order_status', 'customer_age']
Number of columns: 20


### `df.index` – Viewing the Index

In [109]:
print("=== DataFrame Index (df.index) ===")
print("Index:", df.index)
print("Index type:", type(df.index))
print("Index range:", f"{df.index.min()} to {df.index.max()}")
print()

=== DataFrame Index (df.index) ===
Index: RangeIndex(start=0, stop=1220, step=1)
Index type: <class 'pandas.core.indexes.range.RangeIndex'>
Index range: 0 to 1219


### Additional Useful Inspection Methods

In [110]:
print("=== Additional Inspection Methods ===")

=== Additional Inspection Methods ===

In [113]:
# Check for missing values
print("Missing values per column:")
print(df.isnull().sum())
print()

Missing values per column:
order_id              0
customer_id           0
customer_name         0
customer_email       52
product_id            0
product_name          0
category              0
brand                98
price                 0
quantity              0
total_amount          0
discount_percent    203
order_date            0
shipping_address     87
city                  0
state                 0
country               0
payment_method        0
order_status          0
customer_age        112
dtype: int64

In [114]:
# Memory usage
print("Memory usage:")
print(df.memory_usage(deep=True))
print()

Memory usage:
Index                 132
order_id            69540
customer_id         70760
customer_name       75980
customer_email      86054
product_id          70760
product_name        73078
category            69036
brand               65407
price                9760
quantity             9760
total_amount         9760
discount_percent     9760
order_date          71980
shipping_address    72390
city                70970
state               62220
country             66474
payment_method      71754
order_status        70051
customer_age         9760
dtype: int64

In [115]:
# Unique values in categorical columns
if 'category' in df.columns:
    print("Unique categories:")
    print(df['category'].unique())
    print(f"Number of unique categories: {df['category'].nunique()}")
print()

Unique categories:
['Books' 'Electronics' 'Sports' 'Toys' 'Beauty' 'Clothing' 'Home & Garden']
Number of unique categories: 7

### Exercise: Inspect Your Data

Try these commands on the dataset:
1. Show the first 10 rows
2. Get info about the dataset
3. Show summary statistics
4. Check the data types
5. Count missing values

In [ ]:
print("=== Exercise Solutions ===")
print("1. First 10 rows:")
print(df.head(10))
print()

print("2. Dataset info:")
df.info()
print()

print("3. Summary statistics:")
print(df.describe())
print()

print("4. Data types:")
print(df.dtypes)
print()

print("5. Missing values count:")
print(df.isnull().sum())
print()

In [18]:
# =============================================================================
# MODULE D: BASIC DATA SELECTION IN PANDAS
# =============================================================================

# Module D: Basic Data Selection in Pandas

Data selection is fundamental to data analysis. Let's learn how to select specific columns and rows.

## Column Selection

### Selecting a Single Column (Returns a Series)

In [116]:
df.head()

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
1,ORD-1260,CUST-0293,Angela Lee,angela.lee@email.com,PROD-5706,Dell Laptop,Electronics,HP,882.75,3,2648.25,20.0,2025-02-19,8232 Second Ave,Jacksonville,FL,Canada,Debit Card,Cancelled,74.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
3,ORD-2011,CUST-0177,Paul Thompson,paul.thompson@email.com,PROD-3154,Dumbbell Set,Sports,Nike,49.62,5,248.10,10.0,2024-11-22,8955 First St,Chicago,IL,Canada,Bank Transfer,Processing,74.0
4,ORD-1755,CUST-0011,James Harris,james.harris@email.com,PROD-8882,Tennis Racket,Sports,Under Armour,74.16,1,74.16,25.0,2024-07-31,6685 Elm St,Dallas,TX,UK,Apple Pay,Processing,24.0

In [118]:
print("=== Single Column Selection ===")

# Select customer names (returns a Series)
customer_names = df['customer_name'] if 'customer_name' in df.columns else df.iloc[:, 1]
print("Customer names (Series):")
print(customer_names.head())
print(f"Type: {type(customer_names)}")
print()

=== Single Column Selection ===
Customer names (Series):
0     Ashley Lewis
1       Angela Lee
2      David Davis
3    Paul Thompson
4     James Harris
Name: customer_name, dtype: object
Type: <class 'pandas.core.series.Series'>

In [119]:
# Select prices
prices = df['price'] if 'price' in df.columns else df.iloc[:, 4]
print("Prices (Series):")
print(prices.head())
print()

Prices (Series):
0     19.87
1    882.75
2     73.08
3     49.62
4     74.16
Name: price, dtype: float64

In [121]:
price = df['price']
price

0        19.87
1       882.75
2        73.08
3        49.62
4        74.16
         ...
1215    199.45
1216    113.35
1217    297.50
1218     61.17
1219    297.33
Name: price, Length: 1220, dtype: float64


### Selecting Multiple Columns (Returns a DataFrame)

In [ ]:
print("=== Multiple Column Selection ===")

# Select multiple columns using a list
if all(col in df.columns for col in ['customer_name', 'product_name', 'price']):
    selected_columns = df[['customer_name', 'product_name', 'price']]
else:
    # Use positional selection if column names don't match
    selected_columns = df.iloc[:, [1, 2, 4]]

print("Selected columns (DataFrame):")
print(selected_columns.head())
print(f"Type: {type(selected_columns)}")
print(f"Shape: {selected_columns.shape}")
print()

In [122]:
df[['customer_name', 'product_name', 'price']]

         customer_name       product_name   price
0         Ashley Lewis  Business Strategy   19.87
1           Angela Lee        Dell Laptop  882.75
2          David Davis    Web Development   73.08
3        Paul Thompson       Dumbbell Set   49.62
4         James Harris      Tennis Racket   74.16
...                ...                ...     ...
1215       Lisa Taylor             Jacket  199.45
1216  Anthony Martinez     Vacuum Cleaner  113.35
1217      Mark Ramirez         Bed Sheets  297.50
1218      Daniel Jones         Bed Sheets   61.17
1219       James Clark        MacBook Pro  297.33

[1220 rows x 3 columns]

In [ ]:
# You can also store column names in a variable
cols_of_interest = ['order_id', 'total_amount'] if all(col in df.columns for col in ['order_id', 'total_amount']) else [df.columns[0], df.columns[-3]]
subset_df = df[cols_of_interest]
print("Subset DataFrame:")
print(subset_df.head())
print()

## Row Selection with loc and iloc

### `df.loc[]` - Label-based Indexing

`loc` is used for label-based data selection, where you can select data by the index labels or boolean conditions.

In [123]:
df.head()

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
1,ORD-1260,CUST-0293,Angela Lee,angela.lee@email.com,PROD-5706,Dell Laptop,Electronics,HP,882.75,3,2648.25,20.0,2025-02-19,8232 Second Ave,Jacksonville,FL,Canada,Debit Card,Cancelled,74.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
3,ORD-2011,CUST-0177,Paul Thompson,paul.thompson@email.com,PROD-3154,Dumbbell Set,Sports,Nike,49.62,5,248.10,10.0,2024-11-22,8955 First St,Chicago,IL,Canada,Bank Transfer,Processing,74.0
4,ORD-1755,CUST-0011,James Harris,james.harris@email.com,PROD-8882,Tennis Racket,Sports,Under Armour,74.16,1,74.16,25.0,2024-07-31,6685 Elm St,Dallas,TX,UK,Apple Pay,Processing,24.0

In [125]:
print("=== df.loc[] - Label-based Indexing ===")

# Select specific rows by index label
print("Row with index 0:")
print(df.loc[0])
print()

=== df.loc[] - Label-based Indexing ===
Row with index 0:
order_id                          ORD-1543
customer_id                      CUST-0225
customer_name                 Ashley Lewis
customer_email      ashley.lewis@email.com
product_id                       PROD-5566
product_name             Business Strategy
category                             Books
brand                             O'Reilly
price                                19.87
quantity                                 2
total_amount                         39.74
discount_percent                      20.0
order_date                      2023-11-11
shipping_address           8944 Second Ave
city                              New York
state                                   NY
country                            Germany
payment_method                      PayPal
order_status                     Completed
customer_age                          70.0
Name: 0, dtype: object

In [127]:
df.loc[5:10]

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
5,ORD-1311,CUST-0022,Paul Clark,paul.clark@email.com,PROD-8594,Dumbbell Set,Sports,Spalding,82.87,1,82.87,10.0,2025-03-08,4813 First St,San Francisco,CA,USA,PayPal,Cancelled,59.0
6,ORD-1756,CUST-0101,Andrew Davis,andrew.davis@email.com,PROD-4952,Board Game,Toys,Mattel,57.92,4,231.68,20.0,2023-06-08,2344 Oak Ave,Chicago,IL,USA,Debit Card,Completed,44.0
7,ORD-1468,CUST-0172,John Davis,john.davis@email.com,PROD-1180,Running Shoes,Sports,Nike,231.83,3,695.49,5.0,2025-03-06,9440 Second Ave,Los Angeles,CA,Canada,Credit Card,Processing,48.0
8,ORD-1211,CUST-0047,Paul Jones,paul.jones@email.com,PROD-4634,Tennis Racket,Sports,NaN,123.83,5,619.15,NaN,2024-06-19,4793 Elm St,Fort Worth,TX,Germany,Apple Pay,Completed,70.0
9,ORD-1156,CUST-0170,Robert Miller,robert.miller@email.com,PROD-5873,Basketball,Sports,Wilson,86.51,1,86.51,20.0,2024-10-06,7105 Main St,Phoenix,AZ,USA,Bank Transfer,Processing,24.0
10,ORD-2109,CUST-0205,Lisa Rodriguez,lisa.rodriguez@email.com,PROD-1204,Face Cream,Beauty,Chanel,29.52,3,88.56,25.0,2024-05-03,7265 Elm St,Chicago,IL,Australia,Apple Pay,Shipped,64.0

In [131]:
# Select multiple rows by index labels
print("Rows 0, 2, and 4:")
df.loc[[0, 2, 4]]

Rows 0, 2, and 4:

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
4,ORD-1755,CUST-0011,James Harris,james.harris@email.com,PROD-8882,Tennis Racket,Sports,Under Armour,74.16,1,74.16,25.0,2024-07-31,6685 Elm St,Dallas,TX,UK,Apple Pay,Processing,24.0

In [135]:
# Select a range of rows (inclusive)
print("Rows 1 to 3 (inclusive):")
df.loc[0:4]

Rows 1 to 3 (inclusive):

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
1,ORD-1260,CUST-0293,Angela Lee,angela.lee@email.com,PROD-5706,Dell Laptop,Electronics,HP,882.75,3,2648.25,20.0,2025-02-19,8232 Second Ave,Jacksonville,FL,Canada,Debit Card,Cancelled,74.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
3,ORD-2011,CUST-0177,Paul Thompson,paul.thompson@email.com,PROD-3154,Dumbbell Set,Sports,Nike,49.62,5,248.10,10.0,2024-11-22,8955 First St,Chicago,IL,Canada,Bank Transfer,Processing,74.0
4,ORD-1755,CUST-0011,James Harris,james.harris@email.com,PROD-8882,Tennis Racket,Sports,Under Armour,74.16,1,74.16,25.0,2024-07-31,6685 Elm St,Dallas,TX,UK,Apple Pay,Processing,24.0

In [ ]:
# Select specific rows and columns
if 'customer_name' in df.columns and 'price' in df.columns:
    print("Rows 0-2, specific columns:")
    print(df.loc[0:2, ['customer_name', 'price']])
else:
    print("Rows 0-2, specific columns:")
    print(df.loc[0:2, [df.columns[1], df.columns[4]]])
print()

### `df.iloc[]` - Integer-position Based Indexing

`iloc` is used for purely integer-location based indexing for selection by position.

In [137]:
df.head()

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
1,ORD-1260,CUST-0293,Angela Lee,angela.lee@email.com,PROD-5706,Dell Laptop,Electronics,HP,882.75,3,2648.25,20.0,2025-02-19,8232 Second Ave,Jacksonville,FL,Canada,Debit Card,Cancelled,74.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
3,ORD-2011,CUST-0177,Paul Thompson,paul.thompson@email.com,PROD-3154,Dumbbell Set,Sports,Nike,49.62,5,248.10,10.0,2024-11-22,8955 First St,Chicago,IL,Canada,Bank Transfer,Processing,74.0
4,ORD-1755,CUST-0011,James Harris,james.harris@email.com,PROD-8882,Tennis Racket,Sports,Under Armour,74.16,1,74.16,25.0,2024-07-31,6685 Elm St,Dallas,TX,UK,Apple Pay,Processing,24.0

In [136]:
print("=== df.iloc[] - Integer-position Based Indexing ===")

# Select specific row by position
print("First row (position 0):")
df.iloc[0]

=== df.iloc[] - Integer-position Based Indexing ===
First row (position 0):

order_id                          ORD-1543
customer_id                      CUST-0225
customer_name                 Ashley Lewis
customer_email      ashley.lewis@email.com
product_id                       PROD-5566
product_name             Business Strategy
category                             Books
brand                             O'Reilly
price                                19.87
quantity                                 2
total_amount                         39.74
discount_percent                      20.0
order_date                      2023-11-11
shipping_address           8944 Second Ave
city                              New York
state                                   NY
country                            Germany
payment_method                      PayPal
order_status                     Completed
customer_age                          70.0
Name: 0, dtype: object

In [138]:
# Select multiple rows by position
print("First, third, and fifth rows:")
df.iloc[[0, 2, 4]]

First, third, and fifth rows:

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
4,ORD-1755,CUST-0011,James Harris,james.harris@email.com,PROD-8882,Tennis Racket,Sports,Under Armour,74.16,1,74.16,25.0,2024-07-31,6685 Elm St,Dallas,TX,UK,Apple Pay,Processing,24.0

In [143]:
# Select a range of rows (exclusive end)
print("Rows 1 to 3 (exclusive end):")
df.iloc[1:4]

Rows 1 to 3 (exclusive end):

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
1,ORD-1260,CUST-0293,Angela Lee,angela.lee@email.com,PROD-5706,Dell Laptop,Electronics,HP,882.75,3,2648.25,20.0,2025-02-19,8232 Second Ave,Jacksonville,FL,Canada,Debit Card,Cancelled,74.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
3,ORD-2011,CUST-0177,Paul Thompson,paul.thompson@email.com,PROD-3154,Dumbbell Set,Sports,Nike,49.62,5,248.10,10.0,2024-11-22,8955 First St,Chicago,IL,Canada,Bank Transfer,Processing,74.0

In [149]:
# Select specific rows and columns by position
print("First 3 rows, columns 1-3:")
df.iloc[0:3, 1:4]

First 3 rows, columns 1-3:

  customer_id customer_name          customer_email
0   CUST-0225  Ashley Lewis  ashley.lewis@email.com
1   CUST-0293    Angela Lee    angela.lee@email.com
2   CUST-0299   David Davis   david.davis@email.com

In [150]:
df.loc[0:3, "customer_id":"customer_email"]

  customer_id  customer_name           customer_email
0   CUST-0225   Ashley Lewis   ashley.lewis@email.com
1   CUST-0293     Angela Lee     angela.lee@email.com
2   CUST-0299    David Davis    david.davis@email.com
3   CUST-0177  Paul Thompson  paul.thompson@email.com

In [151]:
# Select all rows, specific columns
print("All rows, first 3 columns:")
df.iloc[:, 0:3].head()

All rows, first 3 columns:

   order_id customer_id  customer_name
0  ORD-1543   CUST-0225   Ashley Lewis
1  ORD-1260   CUST-0293     Angela Lee
2  ORD-1044   CUST-0299    David Davis
3  ORD-2011   CUST-0177  Paul Thompson
4  ORD-1755   CUST-0011   James Harris

In [ ]:
# Select last 3 rows
print("Last 3 rows:")
print(df.iloc[-3:])
print()


### Common Use Cases for Selecting Specific Rows/Ranges

In [152]:
print("=== Common Selection Patterns ===")

# First and last rows
print("First row:")
df.iloc[0]

=== Common Selection Patterns ===
First row:

order_id                          ORD-1543
customer_id                      CUST-0225
customer_name                 Ashley Lewis
customer_email      ashley.lewis@email.com
product_id                       PROD-5566
product_name             Business Strategy
category                             Books
brand                             O'Reilly
price                                19.87
quantity                                 2
total_amount                         39.74
discount_percent                      20.0
order_date                      2023-11-11
shipping_address           8944 Second Ave
city                              New York
state                                   NY
country                            Germany
payment_method                      PayPal
order_status                     Completed
customer_age                          70.0
Name: 0, dtype: object

In [153]:
print("Last row:")
df.iloc[-1]

Last row:

order_id                         ORD-2127
customer_id                     CUST-0248
customer_name                 James Clark
customer_email      james.clark@email.com
product_id                      PROD-6605
product_name                  MacBook Pro
category                      Electronics
brand                                Asus
price                              297.33
quantity                                4
total_amount                      1189.32
discount_percent                      NaN
order_date                     2024-08-18
shipping_address             1237 Oak Ave
city                               Austin
state                                  TX
country                         Australia
payment_method                  Apple Pay
order_status                      Shipped
customer_age                         18.0
Name: 1219, dtype: object

In [154]:
# Every nth row
print("Every 2nd row (first 10):")
df.iloc[::2].head()

Every 2nd row (first 10):

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
4,ORD-1755,CUST-0011,James Harris,james.harris@email.com,PROD-8882,Tennis Racket,Sports,Under Armour,74.16,1,74.16,25.0,2024-07-31,6685 Elm St,Dallas,TX,UK,Apple Pay,Processing,24.0
6,ORD-1756,CUST-0101,Andrew Davis,andrew.davis@email.com,PROD-4952,Board Game,Toys,Mattel,57.92,4,231.68,20.0,2023-06-08,2344 Oak Ave,Chicago,IL,USA,Debit Card,Completed,44.0
8,ORD-1211,CUST-0047,Paul Jones,paul.jones@email.com,PROD-4634,Tennis Racket,Sports,NaN,123.83,5,619.15,NaN,2024-06-19,4793 Elm St,Fort Worth,TX,Germany,Apple Pay,Completed,70.0

In [156]:
# Random sample of rows
print("Random sample of 3 rows:")
df.sample(5)

Random sample of 3 rows:

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
567,ORD-1032,CUST-0036,Steven Moore,steven.moore@email.com,PROD-3706,Hoodie,Clothing,H&M,64.04,5,320.20,5.0,2024-11-25,6218 First St,San Antonio,TX,UK,Apple Pay,Cancelled,32.0
378,ORD-1355,CUST-0148,Angela Miller,angela.miller@email.com,PROD-6557,Vacuum Cleaner,Home & Garden,West Elm,462.82,4,1851.28,NaN,2024-03-18,6002 First St,Fort Worth,TX,Australia,PayPal,Processing,62.0
728,ORD-1012,CUST-0030,Anthony White,anthony.white@email.com,PROD-8812,Lipstick,Beauty,NaN,79.40,5,397.00,20.0,2023-08-13,3953 First St,Philadelphia,PA,USA,Credit Card,Processing,56.0
436,ORD-1183,CUST-0287,Steven Martin,steven.martin@email.com,PROD-4634,Lipstick,Beauty,Chanel,8.31,3,24.93,10.0,2024-12-03,850 Oak Ave,Indianapolis,IN,UK,Debit Card,Shipped,65.0
1033,ORD-1473,CUST-0067,Daniel Lopez,daniel.lopez@email.com,PROD-7770,Dumbbell Set,Sports,Wilson,161.66,3,484.98,25.0,2023-07-05,9288 Main St,Los Angeles,CA,Canada,PayPal,Completed,28.0

### Exercise: Practice Data Selection

Try these selection tasks:
1. Select the 'product_name' column
2. Select 'customer_name', 'category', and 'total_amount' columns
3. Select rows 5-9 using iloc
4. Select the first 3 rows and last 3 columns using iloc
5. Get the customer name and price for the 10th order

In [ ]:
print("=== Exercise Solutions ===")

# 1. Select product_name column
print("1. Product names:")
product_col = 'product_name' if 'product_name' in df.columns else df.columns[2]
print(df[product_col].head())
print()

# 2. Select multiple columns
print("2. Multiple columns:")
multi_cols = ['customer_name', 'category', 'total_amount']
# Use available columns or fallback to positions
if all(col in df.columns for col in multi_cols):
    print(df[multi_cols].head())
else:
    print(df.iloc[:, [1, 3, 6]].head())
print()

# 3. Select rows 5-9 using iloc
print("3. Rows 5-9:")
if len(df) > 9:
    print(df.iloc[5:10])
else:
    print("Dataset too small, showing available rows:")
    print(df.iloc[1:])
print()

# 4. First 3 rows, last 3 columns
print("4. First 3 rows, last 3 columns:")
print(df.iloc[0:3, -3:])
print()

# 5. Customer name and price for 10th order
print("5. 10th order details:")
if len(df) >= 10:
    customer_col = 'customer_name' if 'customer_name' in df.columns else df.columns[1]
    price_col = 'price' if 'price' in df.columns else df.columns[4]
    print(df.loc[9, [customer_col, price_col]])
else:
    print("Dataset has fewer than 10 rows")
print()

In [ ]:
# =============================================================================
# MODULE E: ADVANCED SELECTION & DATA CLEANING WITH PANDAS
# =============================================================================

# Module E: Advanced Selection & Data Cleaning with Pandas

## Quick Recap of Previous Modules

So far we've learned:
- **Series and DataFrames**: Core pandas data structures
- **Loading Data**: Using pd.read_csv() and inspecting with head(), info(), describe()
- **Basic Selection**: Selecting columns and rows with loc[] and iloc[]

Now let's move to more advanced selection techniques and data cleaning!

## Boolean Indexing (Conditional Selection)

Boolean indexing allows you to filter data based on conditions.

### Creating Boolean Masks Based on Column Values

In [157]:
df.head()

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
1,ORD-1260,CUST-0293,Angela Lee,angela.lee@email.com,PROD-5706,Dell Laptop,Electronics,HP,882.75,3,2648.25,20.0,2025-02-19,8232 Second Ave,Jacksonville,FL,Canada,Debit Card,Cancelled,74.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
3,ORD-2011,CUST-0177,Paul Thompson,paul.thompson@email.com,PROD-3154,Dumbbell Set,Sports,Nike,49.62,5,248.10,10.0,2024-11-22,8955 First St,Chicago,IL,Canada,Bank Transfer,Processing,74.0
4,ORD-1755,CUST-0011,James Harris,james.harris@email.com,PROD-8882,Tennis Racket,Sports,Under Armour,74.16,1,74.16,25.0,2024-07-31,6685 Elm St,Dallas,TX,UK,Apple Pay,Processing,24.0

In [164]:
expensive_mask = df['price'] > 100
expensive_mask.sum()

601

In [162]:
print("=== Boolean Indexing ===")

# Create boolean masks
print("Boolean mask for expensive products (price > 100):")
expensive_mask = df['price'] > 100
print(expensive_mask.head())
print(f"Type: {type(expensive_mask)}")
print()

=== Boolean Indexing ===
Boolean mask for expensive products (price > 100):
0    False
1     True
2    False
3    False
4    False
Name: price, dtype: bool
Type: <class 'pandas.core.series.Series'>

In [159]:
# Check how many True/False values
print(f"Expensive products: {expensive_mask.sum()}")
print(f"Affordable products: {(~expensive_mask).sum()}")
print()

Expensive products: 601
Affordable products: 619


### Applying Masks to Filter DataFrames

In [168]:
print("=== Filtering with Boolean Masks ===")

# Apply the mask to get expensive products
expensive_products = df[expensive_mask]
print("Expensive products (price > 100):")
expensive_products.head()

=== Filtering with Boolean Masks ===
Expensive products (price > 100):

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
1,ORD-1260,CUST-0293,Angela Lee,angela.lee@email.com,PROD-5706,Dell Laptop,Electronics,HP,882.75,3,2648.25,20.0,2025-02-19,8232 Second Ave,Jacksonville,FL,Canada,Debit Card,Cancelled,74.0
7,ORD-1468,CUST-0172,John Davis,john.davis@email.com,PROD-1180,Running Shoes,Sports,Nike,231.83,3,695.49,5.0,2025-03-06,9440 Second Ave,Los Angeles,CA,Canada,Credit Card,Processing,48.0
8,ORD-1211,CUST-0047,Paul Jones,paul.jones@email.com,PROD-4634,Tennis Racket,Sports,NaN,123.83,5,619.15,NaN,2024-06-19,4793 Elm St,Fort Worth,TX,Germany,Apple Pay,Completed,70.0
13,ORD-1495,CUST-0166,Anna Thompson,anna.thompson@email.com,PROD-7044,Jeans,Clothing,Nike,165.99,5,829.95,25.0,2023-07-15,5085 Main St,Dallas,TX,USA,Bank Transfer,Pending,68.0
15,ORD-1524,CUST-0139,Angela Johnson,angela.johnson@email.com,PROD-8070,Dining Table,Home & Garden,Cuisinart,251.86,2,503.72,NaN,2023-07-18,6315 Elm St,New York,NY,Canada,Credit Card,Processing,42.0

In [171]:
df[df['category'] == 'Books']

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
11,ORD-1712,CUST-0199,Paul Anderson,paul.anderson@email.com,PROD-7188,Data Science Handbook,Books,O'Reilly,21.79,4,87.16,10.0,2024-05-18,4862 Oak Ave,Fort Worth,TX,UK,Debit Card,Processing,19.0
16,ORD-1810,CUST-0163,Jane Smith,jane.smith@email.com,PROD-2428,Data Science Handbook,Books,O'Reilly,12.46,3,37.38,15.0,2025-02-11,8680 First St,Indianapolis,IN,USA,Apple Pay,Completed,71.0
17,ORD-1553,CUST-0201,Robert Clark,robert.clark@email.com,PROD-1384,Machine Learning,Books,Wiley,31.15,4,124.60,10.0,2025-03-24,1624 Oak Ave,San Francisco,CA,Australia,Debit Card,Processing,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1162,ORD-1566,CUST-0009,James Clark,james.clark@email.com,PROD-7001,Data Science Handbook,Books,No Starch Press,46.14,4,184.56,25.0,2025-04-07,8316 Oak Ave,Los Angeles,CA,USA,Bank Transfer,Completed,20.0
1180,ORD-1167,CUST-0056,Michelle Williams,michelle.williams@email.com,PROD-5896,Machine Learning,Books,McGraw-Hill,23.19,5,115.95,0.0,2025-01-26,517 Elm St,Fort Worth,TX,UK,Debit Card,Pending,44.0
1189,ORD-1958,CUST-0089,Helen Williams,helen.williams@email.com,PROD-9820,Business Strategy,Books,O'Reilly,20.76,4,83.04,20.0,2024-10-15,1803 Second Ave,Fort Worth,TX,UK,Credit Card,Processing,53.0
1203,ORD-1956,CUST-0211,Robert Johnson,robert.johnson@email.com,PROD-8142,Machine Learning,Books,No Starch Press,27.11,2,54.22,5.0,2025-02-18,NaN,San Jose,CA,Canada,Debit Card,Completed,34.0
1207,ORD-1770,CUST-0025,Brenda Brown,brenda.brown@email.com,PROD-9672,Business Strategy,Books,O'Reilly,61.70,3,185.10,10.0,2025-03-12,8266 Oak Ave,Philadelphia,PA,Germany,Apple Pay,Shipped,66.0

In [ ]:
# Direct filtering (more common approach)
affordable_products = df[df['price'] <= 100]
print("Affordable products (price <= 100):")
affordable_products.head()


### Combining Conditions (`& `for `AND`, `|` for `OR`)

In [172]:
print("=== Combining Multiple Conditions ===")

# AND condition (&) - both conditions must be True
# Note: Use parentheses around each condition!
expensive_electronics = df[(df['price'] > 100) & (df['category'] == 'Electronics')]
print("Expensive Electronics (price > 100 AND category = Electronics):")
expensive_electronics.head()

=== Combining Multiple Conditions ===
Expensive Electronics (price > 100 AND category = Electronics):

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
1,ORD-1260,CUST-0293,Angela Lee,angela.lee@email.com,PROD-5706,Dell Laptop,Electronics,HP,882.75,3,2648.25,20.0,2025-02-19,8232 Second Ave,Jacksonville,FL,Canada,Debit Card,Cancelled,74.0
28,ORD-1332,CUST-0043,James Martin,james.martin@email.com,PROD-2480,Dell Laptop,Electronics,Dell,823.95,2,1647.90,20.0,2024-10-16,9609 Second Ave,Houston,TX,Germany,Bank Transfer,Cancelled,33.0
37,ORD-1618,CUST-0074,Ashley Perez,ashley.perez@email.com,PROD-2725,iPad Air,Electronics,Sony,537.07,3,1611.21,25.0,2024-03-26,8618 Second Ave,Austin,TX,Australia,Apple Pay,Pending,26.0
43,ORD-1114,CUST-0158,Daniel Lopez,daniel.lopez@email.com,PROD-8354,Samsung Galaxy S23,Electronics,Apple,1136.12,5,5680.60,0.0,2023-08-22,9898 Park Rd,Jacksonville,FL,Germany,Debit Card,Completed,42.0
45,ORD-1266,CUST-0023,Lisa Ramirez,lisa.ramirez@email.com,PROD-2690,MacBook Pro,Electronics,Sony,1065.13,3,3195.39,NaN,2024-04-06,4795 Park Rd,San Antonio,TX,UK,Apple Pay,Pending,60.0

In [175]:
# OR condition (|) - either condition can be True
electronics_or_expensive = df[(df['category'] == 'Electronics') | (df['price'] > 500)]
print("Electronics OR expensive products (price > 500):")
electronics_or_expensive.head(20)

Electronics OR expensive products (price > 500):

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
1,ORD-1260,CUST-0293,Angela Lee,angela.lee@email.com,PROD-5706,Dell Laptop,Electronics,HP,882.75,3,2648.25,20.0,2025-02-19,8232 Second Ave,Jacksonville,FL,Canada,Debit Card,Cancelled,74.0
28,ORD-1332,CUST-0043,James Martin,james.martin@email.com,PROD-2480,Dell Laptop,Electronics,Dell,823.95,2,1647.90,20.0,2024-10-16,9609 Second Ave,Houston,TX,Germany,Bank Transfer,Cancelled,33.0
37,ORD-1618,CUST-0074,Ashley Perez,ashley.perez@email.com,PROD-2725,iPad Air,Electronics,Sony,537.07,3,1611.21,25.0,2024-03-26,8618 Second Ave,Austin,TX,Australia,Apple Pay,Pending,26.0
43,ORD-1114,CUST-0158,Daniel Lopez,daniel.lopez@email.com,PROD-8354,Samsung Galaxy S23,Electronics,Apple,1136.12,5,5680.60,0.0,2023-08-22,9898 Park Rd,Jacksonville,FL,Germany,Debit Card,Completed,42.0
45,ORD-1266,CUST-0023,Lisa Ramirez,lisa.ramirez@email.com,PROD-2690,MacBook Pro,Electronics,Sony,1065.13,3,3195.39,NaN,2024-04-06,4795 Park Rd,San Antonio,TX,UK,Apple Pay,Pending,60.0
62,ORD-1050,CUST-0098,Sarah Ramirez,sarah.ramirez@email.com,PROD-1350,iPad Air,Electronics,Samsung,148.63,3,445.89,5.0,2024-12-21,9180 Oak Ave,San Antonio,TX,USA,Apple Pay,Shipped,32.0
64,ORD-1679,CUST-0033,Brenda Williams,brenda.williams@email.com,PROD-4851,Sony Headphones,Electronics,Samsung,229.13,3,687.39,10.0,2023-08-14,8168 First St,Columbus,OH,UK,Apple Pay,Completed,59.0
68,ORD-1932,CUST-0297,Mark Hernandez,mark.hernandez@email.com,PROD-2135,Samsung Galaxy S23,Electronics,Apple,736.35,1,736.35,15.0,2024-06-13,7572 Park Rd,Dallas,TX,UK,Debit Card,Completed,18.0
70,ORD-1363,CUST-0156,Angela Wilson,angela.wilson@email.com,PROD-5256,iPad Air,Electronics,Apple,1272.63,3,3817.89,NaN,2025-03-19,185 First St,Houston,TX,Australia,Bank Transfer,Shipped,55.0
71,ORD-1345,CUST-0256,Lisa Brown,lisa.brown@email.com,PROD-2999,MacBook Pro,Electronics,HP,818.63,5,4093.15,0.0,2024-04-18,7961 First St,Phoenix,AZ,USA,Bank Transfer,Processing,39.0
79,ORD-2122,CUST-0164,Donald Robinson,donald.robinson@email.com,PROD-2310,MacBook Pro,Electronics,HP,1529.02,5,7645.10,20.0,2024-07-03,6729 Second Ave,Columbus,OH,UK,PayPal,Cancelled,74.0
81,ORD-1362,CUST-0208,Steven Miller,steven.miller@email.com,PROD-3065,iPhone 14,Electronics,Logitech,1064.92,5,5324.60,0.0,2024-10-27,2721 Main St,Seattle,WA,UK,Credit Card,Processing,33.0
97,ORD-1110,CUST-0042,Mark Ramirez,mark.ramirez@email.com,PROD-8799,iPhone 14,Electronics,Sony,159.42,1,159.42,0.0,2024-10-15,1662 Second Ave,Columbus,OH,UK,Credit Card,Shipped,73.0
102,ORD-1711,CUST-0229,Robert Davis,robert.davis@email.com,PROD-3464,Dell Laptop,Electronics,HP,1491.37,4,5965.48,15.0,2023-06-15,8153 First St,Seattle,WA,UK,Apple Pay,Pending,49.0
112,ORD-1882,CUST-0180,Kimberly Lee,kimberly.lee@email.com,PROD-1017,iPhone 14,Electronics,Apple,1240.32,4,4961.28,0.0,2025-03-25,1424 Elm St,Chicago,IL,UK,Credit Card,Pending,70.0
120,ORD-1981,CUST-0044,Daniel Williams,daniel.williams@email.com,PROD-6952,Sony Headphones,Electronics,Asus,651.60,1,651.60,15.0,2024-04-01,6098 Elm St,Dallas,TX,Australia,PayPal,Pending,37.0
129,ORD-1876,CUST-0220,Emily Lopez,emily.lopez@email.com,PROD-1383,Sony Headphones,Electronics,Sony,1401.77,2,2803.54,NaN,2023-08-20,5973 First St,Phoenix,AZ,Australia,Apple Pay,Processing,73.0
130,ORD-1781,CUST-0014,Christopher Jones,christopher.jones@email.com,PROD-3876,MacBook Pro,Electronics,HP,1546.81,3,4640.43,10.0,2023-07-15,7247 Second Ave,Columbus,OH,Germany,Credit Card,Cancelled,49.0
134,ORD-1877,CUST-0008,Jessica Williams,jessica.williams@email.com,PROD-3281,Gaming Mouse,Electronics,Logitech,1884.45,4,7537.80,20.0,2024-04-08,4864 Elm St,Houston,TX,Australia,Credit Card,Shipped,42.0
137,ORD-1813,CUST-0014,David Robinson,david.robinson@email.com,PROD-7104,iPhone 14,Electronics,Samsung,1296.37,5,6481.85,5.0,2023-08-05,1996 Park Rd,San Diego,CA,Canada,Bank Transfer,Completed,38.0

In [ ]:
# Multiple conditions with AND
specific_orders = df[(df['price'] > 50) & (df['quantity'] >= 2) & (df['price'] < 200)]
print("Specific orders (price 50-200 AND quantity >= 2):")
print(specific_orders.head())
print()

In [178]:
# NOT condition (~)

non_electronics = df[~(df['category'] == 'Electronics')]
print("Non-Electronics products:")
non_electronics.head(15)

Non-Electronics products:

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
0,ORD-1543,CUST-0225,Ashley Lewis,ashley.lewis@email.com,PROD-5566,Business Strategy,Books,O'Reilly,19.87,2,39.74,20.0,2023-11-11,8944 Second Ave,New York,NY,Germany,PayPal,Completed,70.0
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
3,ORD-2011,CUST-0177,Paul Thompson,paul.thompson@email.com,PROD-3154,Dumbbell Set,Sports,Nike,49.62,5,248.10,10.0,2024-11-22,8955 First St,Chicago,IL,Canada,Bank Transfer,Processing,74.0
4,ORD-1755,CUST-0011,James Harris,james.harris@email.com,PROD-8882,Tennis Racket,Sports,Under Armour,74.16,1,74.16,25.0,2024-07-31,6685 Elm St,Dallas,TX,UK,Apple Pay,Processing,24.0
5,ORD-1311,CUST-0022,Paul Clark,paul.clark@email.com,PROD-8594,Dumbbell Set,Sports,Spalding,82.87,1,82.87,10.0,2025-03-08,4813 First St,San Francisco,CA,USA,PayPal,Cancelled,59.0
6,ORD-1756,CUST-0101,Andrew Davis,andrew.davis@email.com,PROD-4952,Board Game,Toys,Mattel,57.92,4,231.68,20.0,2023-06-08,2344 Oak Ave,Chicago,IL,USA,Debit Card,Completed,44.0
7,ORD-1468,CUST-0172,John Davis,john.davis@email.com,PROD-1180,Running Shoes,Sports,Nike,231.83,3,695.49,5.0,2025-03-06,9440 Second Ave,Los Angeles,CA,Canada,Credit Card,Processing,48.0
8,ORD-1211,CUST-0047,Paul Jones,paul.jones@email.com,PROD-4634,Tennis Racket,Sports,NaN,123.83,5,619.15,NaN,2024-06-19,4793 Elm St,Fort Worth,TX,Germany,Apple Pay,Completed,70.0
9,ORD-1156,CUST-0170,Robert Miller,robert.miller@email.com,PROD-5873,Basketball,Sports,Wilson,86.51,1,86.51,20.0,2024-10-06,7105 Main St,Phoenix,AZ,USA,Bank Transfer,Processing,24.0
10,ORD-2109,CUST-0205,Lisa Rodriguez,lisa.rodriguez@email.com,PROD-1204,Face Cream,Beauty,Chanel,29.52,3,88.56,25.0,2024-05-03,7265 Elm St,Chicago,IL,Australia,Apple Pay,Shipped,64.0
11,ORD-1712,CUST-0199,Paul Anderson,paul.anderson@email.com,PROD-7188,Data Science Handbook,Books,O'Reilly,21.79,4,87.16,10.0,2024-05-18,4862 Oak Ave,Fort Worth,TX,UK,Debit Card,Processing,19.0
12,ORD-1410,CUST-0128,Helen Perez,helen.perez@email.com,PROD-6270,Dress,Clothing,Gap,48.96,1,48.96,NaN,2024-10-07,NaN,Chicago,IL,Canada,PayPal,Shipped,29.0
13,ORD-1495,CUST-0166,Anna Thompson,anna.thompson@email.com,PROD-7044,Jeans,Clothing,Nike,165.99,5,829.95,25.0,2023-07-15,5085 Main St,Dallas,TX,USA,Bank Transfer,Pending,68.0
14,ORD-1701,CUST-0199,Kimberly Lee,kimberly.lee@email.com,PROD-9354,LEGO Set,Toys,Hasbro,23.09,1,23.09,0.0,2024-12-22,6874 Elm St,Philadelphia,PA,Canada,Bank Transfer,Shipped,44.0
15,ORD-1524,CUST-0139,Angela Johnson,angela.johnson@email.com,PROD-8070,Dining Table,Home & Garden,Cuisinart,251.86,2,503.72,NaN,2023-07-18,6315 Elm St,New York,NY,Canada,Credit Card,Processing,42.0

## Handling Missing Data

Missing data is common in real-world datasets. Let's learn how to identify and handle it.

### Identifying Missing Values: `df.isnull().sum()`

In [179]:
print("=== Identifying Missing Data ===")

# Let's add some missing values for demonstration
df_with_missing = df.copy()

# Check for missing values
print("Missing values per column:")
df_with_missing.isnull().sum()

=== Identifying Missing Data ===
Missing values per column:

order_id              0
customer_id           0
customer_name         0
customer_email       52
product_id            0
product_name          0
category              0
brand                98
price                 0
quantity              0
total_amount          0
discount_percent    203
order_date            0
shipping_address     87
city                  0
state                 0
country               0
payment_method        0
order_status          0
customer_age        112
dtype: int64

In [181]:
# Check percentage of missing values
print("Percentage of missing values:")
(df_with_missing.isnull().sum() / len(df_with_missing)) * 100

Percentage of missing values:

order_id             0.000000
customer_id          0.000000
customer_name        0.000000
customer_email       4.262295
product_id           0.000000
product_name         0.000000
category             0.000000
brand                8.032787
price                0.000000
quantity             0.000000
total_amount         0.000000
discount_percent    16.639344
order_date           0.000000
shipping_address     7.131148
city                 0.000000
state                0.000000
country              0.000000
payment_method       0.000000
order_status         0.000000
customer_age         9.180328
dtype: float64

In [183]:
df_with_missing.isnull().mean()*100

order_id             0.000000
customer_id          0.000000
customer_name        0.000000
customer_email       4.262295
product_id           0.000000
product_name         0.000000
category             0.000000
brand                8.032787
price                0.000000
quantity             0.000000
total_amount         0.000000
discount_percent    16.639344
order_date           0.000000
shipping_address     7.131148
city                 0.000000
state                0.000000
country              0.000000
payment_method       0.000000
order_status         0.000000
customer_age         9.180328
dtype: float64

In [184]:
# Visualize missing data pattern
print("Rows with any missing values:")
df_with_missing[df_with_missing.isnull().any(axis=1)].head()

Rows with any missing values:

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
8,ORD-1211,CUST-0047,Paul Jones,paul.jones@email.com,PROD-4634,Tennis Racket,Sports,NaN,123.83,5,619.15,NaN,2024-06-19,4793 Elm St,Fort Worth,TX,Germany,Apple Pay,Completed,70.0
12,ORD-1410,CUST-0128,Helen Perez,helen.perez@email.com,PROD-6270,Dress,Clothing,Gap,48.96,1,48.96,NaN,2024-10-07,NaN,Chicago,IL,Canada,PayPal,Shipped,29.0
15,ORD-1524,CUST-0139,Angela Johnson,angela.johnson@email.com,PROD-8070,Dining Table,Home & Garden,Cuisinart,251.86,2,503.72,NaN,2023-07-18,6315 Elm St,New York,NY,Canada,Credit Card,Processing,42.0
18,ORD-1754,CUST-0051,William Ramirez,william.ramirez@email.com,PROD-2756,Board Game,Toys,NaN,31.71,3,95.13,5.0,2025-04-06,8782 Oak Ave,Seattle,WA,Germany,Debit Card,Processing,NaN
19,ORD-1424,CUST-0047,Helen Thompson,helen.thompson@email.com,PROD-2060,Dress,Clothing,Gap,134.14,4,536.56,25.0,2024-06-16,3762 Park Rd,Seattle,WA,Australia,Credit Card,Pending,NaN


### Dropping Missing Values: `df.dropna()`

In [186]:
print("=== Dropping Missing Values ===")

# Drop rows with any missing values
df_dropped_rows = df_with_missing.dropna()
print(f"Original shape: {df_with_missing.shape}")
print(f"After dropping rows with missing values: {df_dropped_rows.shape}")
print()

=== Dropping Missing Values ===
Original shape: (1220, 20)
After dropping rows with missing values: (768, 20)

In [187]:
# Drop rows only if ALL values are missing
df_dropped_all = df_with_missing.dropna(how='all')
print(f"After dropping rows where ALL values are missing: {df_dropped_all.shape}")
print()

After dropping rows where ALL values are missing: (1220, 20)

In [188]:
# Drop columns with missing values
df_dropped_cols = df_with_missing.dropna(axis=1)
print(f"After dropping columns with missing values: {df_dropped_cols.shape}")
print()

After dropping columns with missing values: (1220, 15)

In [190]:
# Drop rows with missing values in specific columns
df_dropped_specific = df_with_missing.dropna(subset=['brand'])
print(f"After dropping rows with missing prices: {df_dropped_specific.shape}")
print()

After dropping rows with missing prices: (1122, 20)

In [ ]:
# Use thresh parameter - keep rows with at least N non-null values
df_thresh = df_with_missing.dropna(thresh=len(df_with_missing.columns) - 1)  # Allow 1 missing value
print(f"After using thresh (allow 1 missing value): {df_thresh.shape}")
print()


### Filling Missing Values: `df.fillna()`

In [ ]:
print("=== Filling Missing Values ===")

# Fill with a constant value
df_filled_constant = df_with_missing.fillna('Unknown')
print("After filling with 'Unknown':")
print(df_filled_constant.isnull().sum())
print()

# Fill different columns with different values
fill_values = {'customer_name': 'Anonymous Customer', 'price': 0}
df_filled_dict = df_with_missing.fillna(value=fill_values)
print("After filling with dictionary:")
print(df_filled_dict.isnull().sum())
print()

# Fill with statistical measures (for numeric columns)
if 'price' in df_with_missing.columns:
    # Fill missing prices with mean
    mean_price = df_with_missing['price'].mean()
    df_filled_mean = df_with_missing.copy()
    df_filled_mean['price'].fillna(mean_price, inplace=True)
    print(f"Missing prices filled with mean ({mean_price:.2f}):")
    print(df_filled_mean['price'].isnull().sum())
    print()
    
    # Fill with median
    median_price = df_with_missing['price'].median()
    df_filled_median = df_with_missing.copy()
    df_filled_median['price'].fillna(median_price, inplace=True)
    print(f"Missing prices filled with median ({median_price:.2f}):")
    print(df_filled_median['price'].isnull().sum())
    print()

# Forward fill (use previous value)
df_ffill = df_with_missing.fillna(method='ffill')
print("After forward fill:")
print(df_ffill.isnull().sum())
print()

## Handling Duplicates

Duplicate records can skew analysis results. Let's learn to identify and remove them.

### Identifying Duplicates: `df.duplicated()`

In [ ]:

print("=== Identifying Duplicates ===")

# Add some duplicate rows for demonstration
df_with_dups = df.copy()
# Add the first few rows again as duplicates
df_with_dups = pd.concat([df_with_dups, df_with_dups.head(3)], ignore_index=True)

# Check for duplicates
print(f"Original shape: {df.shape}")
print(f"With duplicates shape: {df_with_dups.shape}")
print()

# Find duplicate rows
duplicated_mask = df_with_dups.duplicated()
print(f"Number of duplicate rows: {duplicated_mask.sum()}")
print()

# Show which rows are duplicates
print("Duplicate rows:")
print(df_with_dups[duplicated_mask])
print()

# Check duplicates based on specific columns
if 'order_id' in df_with_dups.columns:
    order_duplicates = df_with_dups.duplicated(subset=['order_id'])
    print(f"Duplicate order IDs: {order_duplicates.sum()}")
    print()

# Keep different duplicates (first, last, False)
print("Duplicated (keep='first'):", df_with_dups.duplicated(keep='first').sum())
print("Duplicated (keep='last'):", df_with_dups.duplicated(keep='last').sum())
print("Duplicated (keep=False):", df_with_dups.duplicated(keep=False).sum())
print()


### Dropping Duplicates: `df.drop_duplicates()`

In [ ]:

print("=== Dropping Duplicates ===")

# Drop duplicate rows
df_no_dups = df_with_dups.drop_duplicates()
print(f"After dropping duplicates: {df_no_dups.shape}")
print()

# Drop duplicates based on specific columns
if 'order_id' in df_with_dups.columns:
    df_unique_orders = df_with_dups.drop_duplicates(subset=['order_id'])
    print(f"After dropping duplicate order IDs: {df_unique_orders.shape}")
    print()

# Keep last occurrence instead of first
df_keep_last = df_with_dups.drop_duplicates(keep='last')
print(f"After dropping duplicates (keep='last'): {df_keep_last.shape}")
print()

## Basic Data Type Conversion

Sometimes data types need to be changed for proper analysis.

### `df['column'].astype()`

In [ ]:

print("=== Data Type Conversion ===")

# Show current data types
print("Current data types:")
print(df.dtypes)
print()

# Create a copy for type conversion examples
df_converted = df.copy()

# Convert numeric column to string
if 'price' in df_converted.columns:
    print("Converting price to string:")
    df_converted['price_str'] = df_converted['price'].astype(str)
    print(f"Original price type: {df_converted['price'].dtype}")
    print(f"Converted price type: {df_converted['price_str'].dtype}")
    print()

# Convert string to numeric (if applicable)
if 'order_id' in df_converted.columns:
    # Extract numeric part from order_id for demonstration
    df_converted['order_number'] = df_converted['order_id'].str.extract('(\d+)').astype(int)
    print("Extracted order numbers:")
    print(df_converted[['order_id', 'order_number']].head())
    print()

# Convert to datetime
if 'order_date' in df_converted.columns:
    print("Converting order_date to datetime:")
    print(f"Original type: {df_converted['order_date'].dtype}")
    df_converted['order_date'] = pd.to_datetime(df_converted['order_date'])
    print(f"Converted type: {df_converted['order_date'].dtype}")
    print("Sample dates:")
    print(df_converted['order_date'].head())
    print()

# Convert to categorical (saves memory for repeated strings)
if 'category' in df_converted.columns:
    print("Converting category to categorical:")
    print(f"Original type: {df_converted['category'].dtype}")
    df_converted['category'] = df_converted['category'].astype('category')
    print(f"Converted type: {df_converted['category'].dtype}")
    print("Categories:")
    print(df_converted['category'].cat.categories)
    print()

### Exercise: Data Cleaning Practice

Practice these data cleaning tasks:
1. Filter products with price > 50 AND quantity > 1
2. Find all orders from 'New York' OR 'Los Angeles'
3. Create a dataset with no missing values
4. Remove any duplicate rows
5. Convert the order_date to datetime format

In [ ]:
print("=== Data Cleaning Exercise Solutions ===")

# Use the original df for exercises
exercise_df = df.copy()

# Add some sample data if columns don't exist
if 'quantity' not in exercise_df.columns:
    exercise_df['quantity'] = np.random.randint(1, 5, len(exercise_df))

if 'city' not in exercise_df.columns:
    cities = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
    exercise_df['city'] = np.random.choice(cities, len(exercise_df))

# 1. Filter products with price > 50 AND quantity > 1
print("1. Products with price > 50 AND quantity > 1:")
filtered_products = exercise_df[(exercise_df['price'] > 50) & (exercise_df['quantity'] > 1)]
print(f"Found {len(filtered_products)} products matching criteria")
print(filtered_products.head())
print()

# 2. Orders from New York OR Los Angeles
print("2. Orders from New York OR Los Angeles:")
city_filtered = exercise_df[(exercise_df['city'] == 'New York') | (exercise_df['city'] == 'Los Angeles')]
print(f"Found {len(city_filtered)} orders from these cities")
print(city_filtered.head())
print()

# 3. Dataset with no missing values
print("3. Dataset with no missing values:")
clean_df = exercise_df.dropna()
print(f"Original shape: {exercise_df.shape}")
print(f"After removing missing values: {clean_df.shape}")
print()

# 4. Remove duplicate rows
print("4. Remove duplicate rows:")
no_dups_df = exercise_df.drop_duplicates()
print(f"Original shape: {exercise_df.shape}")
print(f"After removing duplicates: {no_dups_df.shape}")
print()

# 5. Convert order_date to datetime
print("5. Convert order_date to datetime:")
if 'order_date' in exercise_df.columns:
    exercise_df['order_date'] = pd.to_datetime(exercise_df['order_date'])
    print(f"order_date type: {exercise_df['order_date'].dtype}")
    print("Sample converted dates:")
    print(exercise_df['order_date'].head())
else:
    print("order_date column not found")
print()

In [2]:
# =============================================================================
# MODULE F: DATA GROUPING & AGGREGATION
# =============================================================================

# Module F: Data Grouping & Aggregation

## The `groupby()` Operation

The groupby operation is one of the most powerful features in pandas. It allows you to:
1. **Split** data into groups based on some criteria
2. **Apply** a function to each group independently  
3. **Combine** the results into a data structure

This is known as the **Split-Apply-Combine** paradigm.

### Concept of Split-Apply-Combine

In [ ]:

print("=== Understanding Split-Apply-Combine ===")
print("1. SPLIT: Divide data into groups based on some criteria")
print("2. APPLY: Apply a function (like mean, sum, count) to each group")
print("3. COMBINE: Combine the results into a final data structure")
print()

# Prepare data for groupby examples
groupby_df = df.copy()

# Ensure we have the necessary columns
if 'category' not in groupby_df.columns:
    categories = ['Electronics', 'Clothing', 'Books', 'Home & Garden', 'Sports']
    groupby_df['category'] = np.random.choice(categories, len(groupby_df))

if 'city' not in groupby_df.columns:
    cities = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
    groupby_df['city'] = np.random.choice(cities, len(groupby_df))


### Grouping by One Column

In [ ]:

print("=== Grouping by Single Column ===")

# Group by category
category_groups = groupby_df.groupby('category')
print(f"GroupBy object: {category_groups}")
print(f"Number of groups: {category_groups.ngroups}")
print("Group keys:", list(category_groups.groups.keys()))
print()

# See the groups
print("Groups and their indices:")
for name, group in category_groups:
    print(f"Group '{name}': {len(group)} rows")
    break  # Just show first group to save space
print()


### Applying Aggregation Functions

Let's apply various aggregation functions to our grouped data.

In [ ]:

print("=== Aggregation Functions ===")

# Basic aggregations on grouped data
print("1. Sum by category:")
if 'total_amount' in groupby_df.columns:
    category_sum = groupby_df.groupby('category')['total_amount'].sum()
    print(category_sum)
elif 'price' in groupby_df.columns:
    category_sum = groupby_df.groupby('category')['price'].sum()
    print(category_sum)
print()

print("2. Mean by category:")
if 'price' in groupby_df.columns:
    category_mean = groupby_df.groupby('category')['price'].mean()
    print(category_mean.round(2))
print()

print("3. Count by category:")
category_count = groupby_df.groupby('category').size()
print(category_count)
print()

print("4. Multiple statistics:")
if 'price' in groupby_df.columns:
    category_stats = groupby_df.groupby('category')['price'].agg(['count', 'mean', 'median', 'std'])
    print(category_stats.round(2))
print()


### Different Aggregation Functions

In [ ]:

print("=== Various Aggregation Functions ===")

# sum(): Total values
print("sum() - Total sales by category:")
if 'total_amount' in groupby_df.columns:
    print(groupby_df.groupby('category')['total_amount'].sum().round(2))
print()

# mean(): Average values  
print("mean() - Average price by category:")
if 'price' in groupby_df.columns:
    print(groupby_df.groupby('category')['price'].mean().round(2))
print()

# median(): Middle value
print("median() - Median price by category:")
if 'price' in groupby_df.columns:
    print(groupby_df.groupby('category')['price'].median().round(2))
print()

# count(): Count non-null values
print("count() - Count of orders by category:")
print(groupby_df.groupby('category')['order_id'].count())
print()

# std(): Standard deviation
print("std() - Price standard deviation by category:")
if 'price' in groupby_df.columns:
    print(groupby_df.groupby('category')['price'].std().round(2))
print()

# size(): Count all rows (including null)
print("size() - Total rows by category:")
print(groupby_df.groupby('category').size())
print()


### Using agg() for Multiple Operations

In [ ]:

print("=== Using agg() for Custom Aggregations ===")

# Apply multiple functions at once
if 'price' in groupby_df.columns:
    price_analysis = groupby_df.groupby('category')['price'].agg({
        'count': 'count',
        'total': 'sum',
        'average': 'mean',
        'median': 'median',
        'min_price': 'min',
        'max_price': 'max',
        'std_dev': 'std'
    })
    print("Comprehensive price analysis by category:")
    print(price_analysis.round(2))
    print()

# Apply different functions to different columns
if all(col in groupby_df.columns for col in ['price', 'quantity']):
    multi_col_agg = groupby_df.groupby('category').agg({
        'price': ['mean', 'max', 'min'],
        'quantity': ['sum', 'mean'],
        'order_id': 'count'
    })
    print("Multiple columns aggregation:")
    print(multi_col_agg.round(2))
    print()


### Grouping by Multiple Columns

In [ ]:

print("=== Grouping by Multiple Columns ===")

# Group by category and city
multi_group = groupby_df.groupby(['category', 'city'])
print("Grouping by category and city:")
print("Number of groups:", multi_group.ngroups)
print()

# Aggregate multi-group data
if 'price' in groupby_df.columns:
    multi_group_stats = multi_group['price'].mean().round(2)
    print("Average price by category and city:")
    print(multi_group_stats.head(10))  # Show first 10 to save space
    print()

# Unstack to create a pivot-like table
if 'price' in groupby_df.columns:
    pivot_like = multi_group['price'].mean().unstack(fill_value=0).round(2)
    print("Pivot-like table (category vs city):")
    print(pivot_like)
    print()


### Practical Examples to Illustrate Power of GroupBy

In [ ]:

print("=== Practical Business Examples ===")

# 1. Sales performance by category
print("1. Sales Performance Analysis:")
if all(col in groupby_df.columns for col in ['category', 'total_amount', 'quantity']):
    sales_performance = groupby_df.groupby('category').agg({
        'total_amount': ['sum', 'mean', 'count'],
        'quantity': 'sum'
    }).round(2)
    print(sales_performance)
print()

# 2. Customer analysis by city
print("2. Customer Analysis by City:")
if 'customer_name' in groupby_df.columns:
    city_analysis = groupby_df.groupby('city').agg({
        'customer_name': 'nunique',  # unique customers
        'order_id': 'count',         # total orders
        'price': 'mean'              # average order value
    }).round(2)
    city_analysis.columns = ['Unique_Customers', 'Total_Orders', 'Avg_Order_Value']
    print(city_analysis)
print()

# 3. Product performance analysis
print("3. Top Categories by Revenue:")
if 'total_amount' in groupby_df.columns:
    top_categories = groupby_df.groupby('category')['total_amount'].sum().sort_values(ascending=False)
    print(top_categories.round(2))
print()

# 4. Time-based analysis (if date column exists)
if 'order_date' in groupby_df.columns:
    # Convert to datetime if not already
    groupby_df['order_date'] = pd.to_datetime(groupby_df['order_date'])
    
    # Extract month for analysis
    groupby_df['month'] = groupby_df['order_date'].dt.month
    
    print("4. Monthly Sales Trend:")
    monthly_sales = groupby_df.groupby('month')['total_amount'].sum().round(2)
    print(monthly_sales)
    print()


### Exercise: GroupBy Practice

Practice these groupby operations:
1. Find the total revenue by city
2. Calculate average order value by category
3. Count the number of unique customers per category
4. Find the category with the highest average price
5. Create a summary showing count, mean, and max price by category

In [ ]:

print("=== GroupBy Exercise Solutions ===")

# 1. Total revenue by city
print("1. Total revenue by city:")
if all(col in groupby_df.columns for col in ['city', 'total_amount']):
    city_revenue = groupby_df.groupby('city')['total_amount'].sum().sort_values(ascending=False)
    print(city_revenue.round(2))
elif 'price' in groupby_df.columns:
    city_revenue = groupby_df.groupby('city')['price'].sum().sort_values(ascending=False)
    print(city_revenue.round(2))
print()

# 2. Average order value by category
print("2. Average order value by category:")
if 'total_amount' in groupby_df.columns:
    avg_order_value = groupby_df.groupby('category')['total_amount'].mean().sort_values(ascending=False)
    print(avg_order_value.round(2))
print()

# 3. Unique customers per category
print("3. Number of unique customers per category:")
if 'customer_name' in groupby_df.columns:
    unique_customers = groupby_df.groupby('category')['customer_name'].nunique().sort_values(ascending=False)
    print(unique_customers)
print()

# 4. Category with highest average price
print("4. Category with highest average price:")
if 'price' in groupby_df.columns:
    highest_avg_price = groupby_df.groupby('category')['price'].mean().sort_values(ascending=False)
    print(f"Highest: {highest_avg_price.index[0]} with ${highest_avg_price.iloc[0]:.2f}")
    print("All categories:")
    print(highest_avg_price.round(2))
print()

# 5. Summary statistics by category
print("5. Summary statistics (count, mean, max) by category:")
if 'price' in groupby_df.columns:
    summary_stats = groupby_df.groupby('category')['price'].agg(['count', 'mean', 'max']).round(2)
    print(summary_stats)
print()


# Congratulations! 🎉

You've completed the comprehensive pandas learning journey covering:

* ✅ **Module B**: Pandas data structures (Series and DataFrame)
* ✅ **Module C**: Loading and inspecting data 
* ✅ **Module D**: Basic data selection techniques
* ✅ **Module E**: Advanced selection and data cleaning
* ✅ **Module F**: Data grouping and aggregation

## Next Steps

Now that you have a solid foundation in pandas, you can:

1. **Practice** with your own datasets
2. **Explore** advanced pandas features like:
   - Merging and joining DataFrames
   - Pivot tables and cross-tabulations
   - Time series analysis
   - Advanced string operations
3. **Combine** pandas with other libraries:
   - Matplotlib/Seaborn for visualization
   - Scikit-learn for machine learning
   - Requests for web scraping

## Key Takeaways

- **Data structures**: Series (1D) and DataFrame (2D) are the foundation
- **Inspection**: Always start with head(), info(), describe(), shape
- **Selection**: Use loc[] for labels, iloc[] for positions
- **Cleaning**: Handle missing values and duplicates systematically  
- **Grouping**: Use groupby() for powerful aggregation and analysis

Happy data analyzing! 📊